/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoed1.vista;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyectoed1.modelo.datos.Datos;
import proyectoed1.modelo.datos.Globales;
import proyectoed1.modelo.dominio.Extra;
import proyectoed1.modelo.dominio.Habitacion;
import proyectoed1.modelo.dominio.ListaExtra;
import proyectoed1.modelo.dominio.ListaImagen;
import proyectoed1.modelo.dominio.NodoExtra;

/**
 *
 * @author adeve
 */
public class GUIAgregarHabitacion extends javax.swing.JFrame {

    private static int contador = 0;
   
    private DefaultTableModel modelExtras = new DefaultTableModel(Globales.columnasExtrasSeleccionadas, 0);
    
    private File[] imagenes ;

    public GUIAgregarHabitacion() {

        this.setContentPane(new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral+"\\src\\proyectoed1\\vista\\icons\\wall1.jpg").getImage().getScaledInstance(961, 617, Image.SCALE_DEFAULT))));
        initComponents();
        GridLayout grid = new GridLayout(0, 5);
        grid.setHgap(30);
        panelImagenes.setLayout(grid);
        panelImagenes.setPreferredSize(new Dimension(825, 186));//[825, 186]
        cargarComboExtras();
        restringirCampos();

        //listaImagenes = new ListaImagen();
        //LogicaImagen li = new LogicaImagen();
        //Image img = Toolkit.getDefaultToolkit().getImage("res-1000.png").getScaledInstance(100, 100,java.awt.Image.SCALE_SMOOTH);
        // this.setSize(new Dimension(768, 636));
        tablaExtrasHab.setModel(modelExtras);
    }

    public void cargarComboExtras() {

        
        NodoExtra ne = Datos.getListaExtras().getPrimero();
        while (ne != null) {
            comboExtras.addItem(ne.getExtra().getCodigo() + "-" + ne.getExtra().getDescripcion());
            ne = ne.getSiguiente();
        }

    }

  
    public boolean verificarExtras(String itemCombo) {
        Object[] columnData = new Object[tablaExtrasHab.getRowCount()];
        Object[] rowData = new Object[tablaExtrasHab.getRowCount()];
        for (int i = 0; i < tablaExtrasHab.getRowCount(); i++) {  
            
            if (itemCombo.equals(tablaExtrasHab.getValueAt(i, 0))) {
                return true;
            }
            
        }

        return false;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        campoPrecio = new javax.swing.JTextField();
        campoPersonas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comboExtras = new javax.swing.JComboBox<String>();
        agregarExtra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaExtrasHab = new javax.swing.JTable();
        eliminarExtra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seleccionImgBoton = new javax.swing.JButton();
        eliminarImagenesBoton = new javax.swing.JButton();
        panelImagenes = new javax.swing.JPanel();
        agregarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar habitación");
        setMaximumSize(new java.awt.Dimension(768, 636));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel1.setText("<html> <body> <b style =\"color:white;\"> Descripción: </b></body><html>");

        jLabel2.setText("<html> <body> <b style =\"color:white;\"> Precio: </b></body><html>");

        jLabel3.setText("<html> <body> <b style =\"color:white;\"> Personas: </b></body><html>");

        campoDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDescripcionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(campoDescripcion))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        agregarExtra.setText("+");
        agregarExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarExtraActionPerformed(evt);
            }
        });

        tablaExtrasHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaExtrasHab);

        eliminarExtra.setText("-");
        eliminarExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarExtra)
                    .addComponent(eliminarExtra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Seleccionar imágenes (Max 5):");

        seleccionImgBoton.setText("Seleccionar...");
        seleccionImgBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionImgBotonActionPerformed(evt);
            }
        });

        eliminarImagenesBoton.setText("Vaciar");
        eliminarImagenesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarImagenesBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionImgBoton)
                .addGap(18, 18, 18)
                .addComponent(eliminarImagenesBoton)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(seleccionImgBoton)
                    .addComponent(eliminarImagenesBoton))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImagenesLayout = new javax.swing.GroupLayout(panelImagenes);
        panelImagenes.setLayout(panelImagenesLayout);
        panelImagenesLayout.setHorizontalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        panelImagenesLayout.setVerticalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        agregarHabitacion.setText("Agregar ");
        agregarHabitacion.setToolTipText("");
        agregarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarHabitacion)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(agregarHabitacion)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarExtraActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablaExtrasHab.getModel();
        if (tablaExtrasHab.getSelectedRow() != -1) {
            model.removeRow(tablaExtrasHab.getSelectedRow());
        }
    }//GEN-LAST:event_eliminarExtraActionPerformed

    private void agregarExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarExtraActionPerformed

        if (verificarExtras(comboExtras.getSelectedItem().toString()) == true) {
            JOptionPane.showMessageDialog(null, "Ya se agregó");
        } else {
            modelExtras.addRow(new Object[]{comboExtras.getSelectedItem()});
        }


    }//GEN-LAST:event_agregarExtraActionPerformed

    public void limpiarCampos() {
        campoDescripcion.setText("");
        campoPrecio.setText("");
        campoPersonas.setText("");
        modelExtras.setRowCount(0);
    }

    public static boolean verificarTablaVacia(JTable jTable) {
        if (jTable != null && jTable.getModel() != null) {
            return jTable.getModel().getRowCount() <= 0 ? true : false;
        }
        return false;
    }

    public boolean validarCampos() {
        if (campoDescripcion.getText().equals("") || campoPrecio.getText().equals("") || campoPersonas.getText().equals("") || verificarTablaVacia(tablaExtrasHab) == true) {
            return true;
        }
        return false;
    }

    private void agregarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarHabitacionActionPerformed
        // TODO add your handling code here:

        if (validarCampos() == true) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos correspondientes.");
        } else {
            Habitacion h = new Habitacion();
            
           
            ListaExtra le = new ListaExtra();

          
            try {
                h.setNumHabitacion(Globales.controladorHabitacion.obtenerNuevoID("habitaciones.txt")+1);
            } catch (IOException ex) {
                Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            h.setDescripcion(campoDescripcion.getText());
            h.setPrecio(Integer.parseInt(campoPrecio.getText()));
            h.setCantidadPersonas(Integer.parseInt(campoPersonas.getText()));

            Object[] columnData = new Object[tablaExtrasHab.getRowCount()];
            Object[] rowData = new Object[tablaExtrasHab.getRowCount()];
            for (int i = 0; i < tablaExtrasHab.getRowCount(); i++) {
                Extra e = new Extra();
                String[] splitfila
                        = tablaExtrasHab.getValueAt(i, 0).toString().split("-");

                e.setCodigo(splitfila[0]);
                e.setDescripcion(splitfila[1]);
                Globales.controladorExtra.agregar(le, e);
            }
            h.setListaExtras(le);
         
           h.setImagenes(imagenes);
            
           
            try {
                if (Globales.controladorHabitacion.agregar(Datos.getListaHabitaciones(), h) == true && Globales.controladorHabitacion.archivar("habitaciones.txt", h) == true && Globales.controladorHabitacion.guardarImagenes(imagenes, Globales.rutaGeneral, h.getNumHabitacion()) == true) {
                    JOptionPane.showMessageDialog(null, "Agregado con éxito.");
                   
                    Datos.resetearListaHabitaciones();
                    Datos.iniciarListaHabitaciones();
                    limpiarCampos();
                    this.dispose();
                    new GUIHabitaciones().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al agregar.");
                }
            } catch (IOException ex) {
                Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_agregarHabitacionActionPerformed

    private void seleccionImgBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionImgBotonActionPerformed
       
        Globales.jc.setDialogTitle("Selecciona las imágenes..");
        Globales.jc.setMultiSelectionEnabled(true);

       
        if (Globales.jc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            imagenes = Globales.jc.getSelectedFiles();

            if (imagenes.length > 5) {
                JOptionPane.showMessageDialog(null, "No se puede agregar más de 5 imágenes.");
                imagenes = null;
            } else {
                for (File imagen : imagenes) {
                    imagen.getName();

                    JLabel jlabelpic = new JLabel(new ImageIcon(new ImageIcon(imagen.getAbsolutePath()).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
                    System.out.print(imagen.getAbsolutePath() + "\n");
                   

                    panelImagenes.add(jlabelpic);
                    contador++;
                     
                     
                    if(contador > 5){
                        seleccionImgBoton.setEnabled(false);
                        
                        imagenes = null;
                        contador = 0;
                    }
                    System.out.print(imagen.getName() + "\n");

                }
   
                revalidate();
                repaint();
              
            }
        }

    }//GEN-LAST:event_seleccionImgBotonActionPerformed

    private void eliminarImagenesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarImagenesBotonActionPerformed
       
        panelImagenes.removeAll();
        seleccionImgBoton.setEnabled(true);

        revalidate();
        repaint();
    }//GEN-LAST:event_eliminarImagenesBotonActionPerformed
    
    public void restringirCampos(){
        RestrictedTextField campoDesc = new RestrictedTextField(campoDescripcion);
        RestrictedTextField campoPrec = new RestrictedTextField(campoPrecio);
        RestrictedTextField campoPerson = new RestrictedTextField(campoPersonas);
    
        campoDesc.setAcceptSpace(true);
        campoDesc.setOnlyAlphaNumeric(true);
        campoPrec.setOnlyNums(true);
        campoPerson.setOnlyNums(true);
        
    }
    
    private void campoDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescripcionKeyTyped
      /*  if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
            }
        */
    }//GEN-LAST:event_campoDescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgregarHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarExtra;
    private javax.swing.JButton agregarHabitacion;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoPersonas;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JComboBox<String> comboExtras;
    private javax.swing.JButton eliminarExtra;
    private javax.swing.JButton eliminarImagenesBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelImagenes;
    private javax.swing.JButton seleccionImgBoton;
    private javax.swing.JTable tablaExtrasHab;
    // End of variables declaration//GEN-END:variables
}
