/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoed1.vista;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import proyectoed1.modelo.datos.Datos;
import proyectoed1.modelo.datos.Globales;
import proyectoed1.modelo.dominio.Habitacion;
import proyectoed1.modelo.dominio.ListaHabitacion;
import proyectoed1.modelo.dominio.NodoExtra;
import proyectoed1.modelo.dominio.NodoHabitacion;

/**
 *
 * @author adeve
 */
public class GUIConsultarHabitacion extends javax.swing.JFrame {

    private String[] imagenesNombre;
    private File[] imagenes;
    public static int contador = 1;
    private String valorFiltrado;
    private static NodoHabitacion actual;

    public GUIConsultarHabitacion() {
        Datos.resetearListaHabitaciones();
        Datos.iniciarListaHabitaciones();
        this.setContentPane(new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral + "\\src\\proyectoed1\\vista\\icons\\wall1.jpg").getImage().getScaledInstance(1026, 719, Image.SCALE_DEFAULT))));
        initComponents();
        buttonGroup1.add(ascendenteNumHab);
        buttonGroup1.add(descendenteNumHab);
        buttonGroup2.add(ascendenteCantP);
        buttonGroup2.add(descendenteCantP);
        buttonGroup3.add(ascendentePrecio);
        buttonGroup3.add(descendentePrecio);
        valorFiltrado = "";
        cargarComboExtras();

        GridLayout grid = new GridLayout(0, 5);
        grid.setHgap(30);
        panelDatos.setPreferredSize(new Dimension(980, 421));//[980, 421]
        panelImagenes.setLayout(grid);
        panelImagenes.setPreferredSize(new Dimension(825, 186));//[825, 186]
        cargarListaHabitaciones();
        

    }

    public void cargarComboExtras() {

        NodoExtra ne = Datos.getListaExtras().getPrimero();
        while (ne != null) {
            filtroExtras.addItem(ne.getExtra().getCodigo() + "-" + ne.getExtra().getDescripcion());
            ne = ne.getSiguiente();
        }

    }

    private String quitarUltimoCaracter(String s) {

        return s.substring(0, s.length() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filtroCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filtroExtras = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        filtroPersonas = new javax.swing.JTextField();
        activarFiltroHabitacion = new javax.swing.JCheckBox();
        activarFiltroExtra = new javax.swing.JCheckBox();
        activarFiltroPersonas = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ascendenteNumHab = new javax.swing.JRadioButton();
        descendenteNumHab = new javax.swing.JRadioButton();
        ascendenteCantP = new javax.swing.JRadioButton();
        descendenteCantP = new javax.swing.JRadioButton();
        ascendentePrecio = new javax.swing.JRadioButton();
        descendentePrecio = new javax.swing.JRadioButton();
        panelDatos = new javax.swing.JPanel();
        panelInformacion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numHabitacion = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        cantPersonas = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelExtras = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        extras = new javax.swing.JLabel();
        panelImagenes = new javax.swing.JPanel();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar habitaciones");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel1.setText("<html> <body> <b style =\"color:white;\"> Filtros: </b></body><html>");

        jLabel2.setText("<html> <body> <b style =\"color:white;\"> #Habitación: </b></body><html>");

        filtroCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroCedulaKeyPressed(evt);
            }
        });

        jLabel3.setText("<html> <body> <b style =\"color:white;\"> Extras: </b></body><html>");

        jLabel4.setText("<html> <body> <b style =\"color:white;\"> C.Personas: </b></body><html>");
        jLabel4.setToolTipText("");

        filtroPersonas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroPersonasKeyPressed(evt);
            }
        });

        activarFiltroHabitacion.setText("<html> <body> <b > Filtrar </b></body><html>");
        activarFiltroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarFiltroHabitacionActionPerformed(evt);
            }
        });

        activarFiltroExtra.setText("<html> <body> <b > Filtrar </b></body><html>");
        activarFiltroExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarFiltroExtraActionPerformed(evt);
            }
        });

        activarFiltroPersonas.setText("<html> <body> <b > Filtrar </b></body><html>");
        activarFiltroPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarFiltroPersonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filtroExtras, 0, 180, Short.MAX_VALUE)
                    .addComponent(filtroCedula)
                    .addComponent(filtroPersonas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activarFiltroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarFiltroExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarFiltroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarFiltroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarFiltroExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarFiltroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Orden:");

        jLabel8.setText("Número de habitación:");

        jLabel9.setText("Cantidad de personas:");

        jLabel10.setText("Precio:");

        ascendenteNumHab.setText("Ascendente");
        ascendenteNumHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendenteNumHabActionPerformed(evt);
            }
        });

        descendenteNumHab.setText("Descendente");
        descendenteNumHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendenteNumHabActionPerformed(evt);
            }
        });

        ascendenteCantP.setText("Ascendente");
        ascendenteCantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendenteCantPActionPerformed(evt);
            }
        });

        descendenteCantP.setText("Descendente");
        descendenteCantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendenteCantPActionPerformed(evt);
            }
        });

        ascendentePrecio.setSelected(true);
        ascendentePrecio.setText("Ascendente");
        ascendentePrecio.setActionCommand("");
        ascendentePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendentePrecioActionPerformed(evt);
            }
        });

        descendentePrecio.setText("Descendente");
        descendentePrecio.setToolTipText("");
        descendentePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendentePrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ascendenteCantP)
                            .addComponent(ascendentePrecio)
                            .addComponent(ascendenteNumHab))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descendenteNumHab)
                            .addComponent(descendentePrecio)
                            .addComponent(descendenteCantP))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ascendenteNumHab)
                    .addComponent(descendenteNumHab))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ascendenteCantP)
                    .addComponent(descendenteCantP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ascendentePrecio)
                    .addComponent(descendentePrecio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Descripción: ");

        jLabel12.setText("Num. Habitación:");

        jLabel13.setText("Precio:");

        jLabel14.setText("Cantidad de personas:");

        numHabitacion.setText("jLabel15");

        descripcion.setText("jLabel16");

        precio.setText("jLabel17");

        cantPersonas.setText("jLabel18");

        jLabel19.setText("Información de habitación:");

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(28, 28, 28)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantPersonas)
                            .addComponent(precio)
                            .addComponent(descripcion)
                            .addComponent(numHabitacion)))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numHabitacion))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(descripcion))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(precio))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cantPersonas))
                .addGap(21, 21, 21))
        );

        jLabel20.setText("Extras que se ofrecen:");

        extras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extras.setText("jLabel21");
        extras.setAutoscrolls(true);
        extras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelExtrasLayout = new javax.swing.GroupLayout(panelExtras);
        panelExtras.setLayout(panelExtrasLayout);
        panelExtrasLayout.setHorizontalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(extras))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panelExtrasLayout.setVerticalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(extras)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        panelImagenes.setPreferredSize(new java.awt.Dimension(825, 186));

        javax.swing.GroupLayout panelImagenesLayout = new javax.swing.GroupLayout(panelImagenes);
        panelImagenes.setLayout(panelImagenesLayout);
        panelImagenesLayout.setHorizontalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImagenesLayout.setVerticalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(panelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        botonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoed1/vista/icons/izq.png"))); // NOI18N
        botonAnterior.setMaximumSize(new java.awt.Dimension(77, 23));
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoed1/vista/icons/der.png"))); // NOI18N
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        

        int tamanio = Globales.controladorHabitacion.obtenerTamanioLista(Datos.getListaHabitaciones());

        //NodoHabitacion h = actual;
        if (contador > tamanio) {
            contador = 0;

        }
        actual = actual.getSiguiente();
     //   h = Globales.controladorHabitacion.obtenerHabitacionNodo(contador, Datos.getListaHabitaciones());
        contador++;

        //cargar info
        numHabitacion.setText(String.valueOf(actual.getHabitacion().getNumHabitacion()));
        descripcion.setText(actual.getHabitacion().getDescripcion() );
        precio.setText(String.valueOf(Math.round(actual.getHabitacion().getPrecio())));
        cantPersonas.setText(String.valueOf(actual.getHabitacion().getCantidadPersonas()));

        NodoExtra extra = actual.getHabitacion().getListaExtras().getPrimero();
        String extrasHabitacion = "";
        while (extra != null) {
            extrasHabitacion += extra.getExtra().getDescripcion() + ",";
            extra = extra.getSiguiente();
        }
        extras.setText(quitarUltimoCaracter(extrasHabitacion));

        //cargar imagenes
        for (String s : actual.getHabitacion().getImagenesNombres()) {

            JLabel jlabelpic = new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral + "\\img\\habitaciones\\" + s).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
            panelImagenes.add(jlabelpic);

        }
        imagenesNombre = actual.getHabitacion().getImagenesNombres();
        // imagenes = new File[5];
        imagenes = new File[imagenesNombre.length];
        int i = 0;
        for (String s : imagenesNombre) {
            imagenes[i] = new File(Globales.rutaGeneral + "\\img\\habitaciones\\" + s);
            i++;

        }


    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();
            
        //Nodo actual
        //actual.getAnterior
        //
        
        contador--;
        int tamanio = Globales.controladorHabitacion.obtenerTamanioLista(Datos.getListaHabitaciones());

        NodoHabitacion h =actual;
        if (contador < 0) {
            contador = tamanio;

        }
        
        actual = actual.getAnterior();
        
        //h = Globales.controladorHabitacion.obtenerHabitacionNodo(contador, Datos.getListaHabitaciones());

        //cargar info
        numHabitacion.setText(String.valueOf(actual.getHabitacion().getNumHabitacion()));
        descripcion.setText(actual.getHabitacion().getDescripcion());
        precio.setText(String.valueOf(Math.round(actual.getHabitacion().getPrecio())));
        cantPersonas.setText(String.valueOf(actual.getHabitacion().getCantidadPersonas()));

        NodoExtra extra = actual.getHabitacion().getListaExtras().getPrimero();
        String extrasHabitacion = "";
        while (extra != null) {
            extrasHabitacion += extra.getExtra().getDescripcion() + ",";
            extra = extra.getSiguiente();
        }
        extras.setText(quitarUltimoCaracter(extrasHabitacion));

        //cargar imagenes
        for (String s : h.getHabitacion().getImagenesNombres()) {

            JLabel jlabelpic = new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral + "\\img\\habitaciones\\" + s).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
            panelImagenes.add(jlabelpic);

        }
        
        imagenesNombre = actual.getHabitacion().getImagenesNombres();

        imagenes = new File[imagenesNombre.length];
        int i = 0;
        for (String s : imagenesNombre) {
            imagenes[i] = new File(Globales.rutaGeneral + "\\img\\habitaciones\\" + s);
            i++;

        }


    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void ascendenteNumHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendenteNumHabActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        Globales.controladorHabitacion.ordenarAscNumHabitacion(Datos.getListaHabitaciones());
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_ascendenteNumHabActionPerformed

    private void descendenteNumHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendenteNumHabActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        Globales.controladorHabitacion.ordenarDescNumHabitacion(Datos.getListaHabitaciones());
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_descendenteNumHabActionPerformed

    private void ascendenteCantPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendenteCantPActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();
Globales.controladorHabitacion.ordenarAscCantPersonas(Datos.getListaHabitaciones());
        
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_ascendenteCantPActionPerformed

    private void descendenteCantPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendenteCantPActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();
        Globales.controladorHabitacion.ordenarDesCantPersonas(Datos.getListaHabitaciones());
        
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_descendenteCantPActionPerformed

    private void ascendentePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendentePrecioActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        Globales.controladorHabitacion.ordenarAsccPrecio(Datos.getListaHabitaciones());
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_ascendentePrecioActionPerformed

    private void descendentePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendentePrecioActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        Globales.controladorHabitacion.ordenarDescPrecio(Datos.getListaHabitaciones());
        cargarListaHabitaciones();
        contador = 1;
    }//GEN-LAST:event_descendentePrecioActionPerformed

    private void activarFiltroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarFiltroHabitacionActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();

        if (activarFiltroHabitacion.isSelected()) {

            if (filtroCedula.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo esta vacio");
                filtroCedula.setText("");
            } else if (Globales.controladorHabitacion.verificarHabitacion(Integer.parseInt(filtroCedula.getText()), Datos.getListaHabitaciones()) == false) {
                JOptionPane.showMessageDialog(null, "No existe la habitación solicitada.");
                filtroCedula.setText("");
            } else {
                Habitacion h = Globales.controladorHabitacion.obtenerHabitacion(Integer.parseInt(filtroCedula.getText()), Datos.getListaHabitaciones());
                System.out.print(h.getDescripcion());
                //cargar info
                numHabitacion.setText(String.valueOf(h.getNumHabitacion()));
                descripcion.setText(h.getDescripcion());
                precio.setText(String.valueOf(h.getPrecio()));
                cantPersonas.setText(String.valueOf(h.getCantidadPersonas()));
              
                NodoExtra extra = h.getListaExtras().getPrimero();
                String extrasHabitacion = "";
                while (extra != null) {
                    extrasHabitacion += extra.getExtra().getDescripcion() + ",";
                    extra = extra.getSiguiente();
                }
                extras.setText(quitarUltimoCaracter(extrasHabitacion));

                //cargar imagenes
                for (String s : h.getImagenesNombres()) {

                    JLabel jlabelpic = new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral + "\\img\\habitaciones\\" + s).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
                    panelImagenes.add(jlabelpic);
                   
                }
                imagenesNombre = h.getImagenesNombres();
              
                imagenes = new File[imagenesNombre.length];
                int i = 0;
                for (String s : imagenesNombre) {
                    imagenes[i] = new File(Globales.rutaGeneral + "\\img\\habitaciones\\" + s);
                    i++;

                }

                botonAnterior.setEnabled(false);
                botonSiguiente.setEnabled(false);
            }

        } else {

            cargarListaHabitaciones();
            botonAnterior.setEnabled(true);
            botonSiguiente.setEnabled(true);
            filtroCedula.setText("");
        }

        

    }//GEN-LAST:event_activarFiltroHabitacionActionPerformed

    private void activarFiltroExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarFiltroExtraActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();
         Datos.resetearListaHabitaciones();
         Datos.iniciarListaHabitaciones();
        ListaHabitacion auxiliar = Datos.getListaHabitaciones();

        if (activarFiltroExtra.isSelected()) {
            ListaHabitacion auxiliar2 = Globales.controladorHabitacion.filtrarPorExtras(Datos.getListaHabitaciones(), filtroExtras.getSelectedItem().toString());
            Datos.setListaHabitaciones(auxiliar2);
            cargarListaHabitaciones();

        } else {
            Datos.resetearListaHabitaciones();
            Datos.iniciarListaHabitaciones();
            cargarListaHabitaciones();
        }

        contador = 1;
        
    }//GEN-LAST:event_activarFiltroExtraActionPerformed

    private void activarFiltroPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarFiltroPersonasActionPerformed
        // TODO add your handling code here:
        panelImagenes.removeAll();
       
        ListaHabitacion auxiliar = Datos.getListaHabitaciones();

        if (activarFiltroPersonas.isSelected()) {
            if (filtroPersonas.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo esta vacio");
            } else {
                ListaHabitacion auxiliar2 = Globales.controladorHabitacion.filtrarPorCantidadPersonas(Datos.getListaHabitaciones(), filtroPersonas.getText());
                Datos.setListaHabitaciones(auxiliar2);
                cargarListaHabitaciones();
                filtroPersonas.setText("");
            }

        } else {
            Datos.resetearListaHabitaciones();
            Datos.iniciarListaHabitaciones();
            cargarListaHabitaciones();
        }

        contador = 1;
    }//GEN-LAST:event_activarFiltroPersonasActionPerformed

    private void filtroPersonasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroPersonasKeyPressed
        // TODO add your handling code here:

        valorFiltrado = filtroPersonas.getText();
        int l = valorFiltrado.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE) {
            filtroPersonas.setEditable(true);

        } else {
            filtroPersonas.setEditable(false);
            JOptionPane.showMessageDialog(null, "Solo se permiten números.");
        }
    }//GEN-LAST:event_filtroPersonasKeyPressed

    private void filtroCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroCedulaKeyPressed
        // TODO add your handling code here:
        valorFiltrado = filtroCedula.getText();
        int l = valorFiltrado.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE) {
            filtroCedula.setEditable(true);

        } else {
            filtroCedula.setEditable(false);
            JOptionPane.showMessageDialog(null, "Solo se permiten números.");
        }
    }//GEN-LAST:event_filtroCedulaKeyPressed

    public void cargarListaHabitaciones() {
        
        actual = Datos.getListaHabitaciones().getPrimero();
        numHabitacion.setText(String.valueOf(actual.getHabitacion().getNumHabitacion()));
        descripcion.setText(actual.getHabitacion().getDescripcion());
        precio.setText(String.valueOf(Math.round(actual.getHabitacion().getPrecio())));
        cantPersonas.setText(String.valueOf(actual.getHabitacion().getCantidadPersonas()));
       
        NodoExtra extra = actual.getHabitacion().getListaExtras().getPrimero();
        
        
        
        String extrasHabitacion = "";
        while (extra != null) {
            extrasHabitacion += extra.getExtra().getDescripcion() + ",";
            extra = extra.getSiguiente();
        }
        extras.setText(quitarUltimoCaracter(extrasHabitacion));

        
        for (String s : actual.getHabitacion().getImagenesNombres()) {

            JLabel jlabelpic = new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral + "\\img\\habitaciones\\" + s).getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
            panelImagenes.add(jlabelpic);
            
        }
        imagenesNombre = actual.getHabitacion().getImagenesNombres();
       
        imagenes = new File[imagenesNombre.length];
        int i = 0;
        for (String s : imagenesNombre) {
            imagenes[i] = new File(Globales.rutaGeneral + "\\img\\habitaciones\\" + s);
            i++;

        }

        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConsultarHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activarFiltroExtra;
    private javax.swing.JCheckBox activarFiltroHabitacion;
    private javax.swing.JCheckBox activarFiltroPersonas;
    private javax.swing.JRadioButton ascendenteCantP;
    private javax.swing.JRadioButton ascendenteNumHab;
    private javax.swing.JRadioButton ascendentePrecio;
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel cantPersonas;
    private javax.swing.JRadioButton descendenteCantP;
    private javax.swing.JRadioButton descendenteNumHab;
    private javax.swing.JRadioButton descendentePrecio;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel extras;
    private javax.swing.JTextField filtroCedula;
    private javax.swing.JComboBox<String> filtroExtras;
    private javax.swing.JTextField filtroPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numHabitacion;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelExtras;
    private javax.swing.JPanel panelImagenes;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
