/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoed1.vista;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoed1.modelo.datos.Datos;
import proyectoed1.modelo.datos.Globales;
import proyectoed1.modelo.dominio.NodoReserva;
import proyectoed1.vista.GUIAgregarReserva;
import proyectoed1.vista.GUIVerificarReserva;

/**
 *
 * @author adeve
 */
public class GUIReservas extends javax.swing.JFrame {

    
    private DefaultTableModel model = new DefaultTableModel(Globales.col, 0);


    public GUIReservas() {
        Datos.iniciarListaHabitaciones();
        Datos.iniciarListaReservas();
        Datos.iniciarListaReservasCanceladas();
         this.setContentPane(new JLabel(new ImageIcon(new ImageIcon(Globales.rutaGeneral+"\\src\\proyectoed1\\vista\\icons\\wall1.jpg").getImage().getScaledInstance(724, 499 ,Image.SCALE_DEFAULT))));
        initComponents();
        tablaReservas.setModel(model);
        cargarTabla();
       
    }
    
    public void cargarTabla(){
         NodoReserva actual = Datos.getListaReservas().getPrimero();
        if (Datos.getListaReservas().getPrimero() == null && Datos.getListaReservas().getUltimo() == null) {
            JOptionPane.showMessageDialog(this, "No hay datos de reservas.");

        } else {
            while (actual != null) {
                Object[] data = {
                    actual.getReserva().getNumeroReservacion(), crearFechaAString(actual.getReserva().getFechaActual()), crearFechaAString(actual.getReserva().getFechaInicio()), crearFechaAString( actual.getReserva().getFechaFinal()),
                    actual.getReserva().getCliente().getCedula(), actual.getReserva().getCliente().getNombre()};
                model.addRow(data);

                actual = actual.getSiguiente();
            }
        }
    }
    
    public static String crearFechaAString(Date fechaAux) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        String fecha = sdf.format(fechaAux);

        return fecha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarReserva = new javax.swing.JButton();
        verificarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar reservas");
        setResizable(false);

        agregarReserva.setText("Agregar reserva");
        agregarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarReservaActionPerformed(evt);
            }
        });

        verificarReserva.setText("Verificar reserva");
        verificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarReservaActionPerformed(evt);
            }
        });

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarReserva)
                        .addGap(18, 18, 18)
                        .addComponent(verificarReserva)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarReserva)
                    .addComponent(verificarReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarReservaActionPerformed
        // TODO add your handling code here:}
        this.dispose();
        new GUIAgregarReserva().setVisible(true);
    }//GEN-LAST:event_agregarReservaActionPerformed

    private void verificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarReservaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new GUIVerificarReserva().setVisible(true);
    }//GEN-LAST:event_verificarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReservas;
    private javax.swing.JButton verificarReserva;
    // End of variables declaration//GEN-END:variables
}
